services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: helpdesk-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  redis_data:
